server:
  port: 8088

spring:
  application:
    name: submission-service
  datasource:
    url: ${SUBMISSION_DB_URL}
    username: ${SUBMISSION_DB_USERNAME}
    password: ${SUBMISSION_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    encoding: UTF-8
    validate-on-migrate: true
    baseline-on-migrate: true
    connection-retries: 10
    init-sqls: "SELECT 1"

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 5
      acks: all
      batch-size: 65536
      delivery-timeout-ms: 30000
      linger-ms: 1000
      request-timeout-ms: 10000
      retry-backoff-ms: 1000
      properties:
        enable.idempotence: true
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
      group-id: submission-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      concurrency: 1
      trusted-packages: org.sleepless_artery.submission-service.*
      
  cache:
    type: redis
  data:
    redis:
      host: ${SUBMISSION_REDIS_HOST:}
      port: ${SUBMISSION_REDIS_PORT:6379}
      password: ${SUBMISSION_REDIS_PASSWORD:}


minio:
  url: ${SUBMISSION_MINIO_URL:http://minio:9000}
  accessKey: ${SUBMISSION_MINIO_ACCESS_KEY}
  secretKey: ${SUBMISSION_MINIO_SECRET_KEY}
  bucketName: ${SUBMISSION_MINIO_BUCKET_NAME}


grpc:
  client:
    GLOBAL:
      negotiation-type: plaintext
      keep-alive-time: 30s
      keep-alive-timeout: 20s
      deadline-after: 10s
    user-service:
      address: ${USER_SERVICE_GRPC_URL:static://user-service:9093}
    assignment-service:
      address: ${ASSIGNMENT_SERVICE_GRPC_URL:static://assignment-service:9101}


resilience4j:
  circuitbreaker:
    instances:
      user-service:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
        automatic-transition-from-open-to-half-open-enabled: true
      assignment-service:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
        automatic-transition-from-open-to-half-open-enabled: true
      minio-service:
        failure-rate-threshold: 50
        sliding-window-size: 20
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true


  retry:
    instances:
      user-service:
        max-attempts: 3
        wait-duration: 300ms
        retry-exceptions:
          - io.grpc.StatusRuntimeException
      assignment-service:
        max-attempts: 3
        wait-duration: 300ms
        retry-exceptions:
          - io.grpc.StatusRuntimeException
      minio-service:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - io.minio.errors.MinioException
          - java.net.SocketTimeoutException
          - java.io.IOException


  timelimiter:
    instances:
      minio-service:
        timeout-duration: 5s

  bulkhead:
    instances:
      minio-service:
        max-concurrent-calls: 10
        max-wait-duration: 0


management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /internal/actuator
  endpoint:
    health:
      show-details: always