spring:
  cache:
    type: redis
  data:
    redis:
      cluster:
        nodes: ${SPRING_REDIS_CLUSTER_NODES}
        max-redirects: 3
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
        cluster:
          refresh:
            adaptive: true
            period: 2000ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /internal/actuator
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
    info:
      env:
        enabled: true
  trace:
    http:
      enabled: false

logging:
  level:
    root: WARN
    org:
      springframework:
        web: WARN
        security: WARN
        boot:
          actuate: INFO
      hibernate:
        SQL: ERROR
        type.descriptor.sql.BasicBinder: ERROR
      sleepless_artery:
        auth_service: INFO
    io:
      micrometer: INFO