spring:
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
      sleepless_artery:
        auth_service: DEBUG